version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile_web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  db:
    build: 
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "5432:5432"

